require:
  - rubocop-performance

AllCops:
  Exclude:
    - 'spec/factories/**/*'
    - 'tmp/**/*'
    - 'bin/*'
    - 'Gemfile'
  TargetRubyVersion: 2.6
  NewCops: enable

# Too short methods lead to extraction of single-use methods, which can make
# the code easier to read (by naming things), but can also clutter the class
Metrics/MethodLength: 
  Max: 50

# The guiding principle of classes is SRP, SRP can't be accurately measured by LoC
Metrics/ClassLength:
  Max: 1500

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Style/Documentation:
  Enabled: false 

Style/AccessorGrouping:
  EnforcedStyle: separated

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
