name: Tests

on: push

jobs:
  tests:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.6.9
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6.9
    - name: Install required apt packages
      run: |
        sudo apt-get -y install libpq-dev
    - name: Build
      run: |
        bundle install
    - name: Run tests
      run: |
        bundle exec rspec
